title: Mouse Village
description: A website to showcase the Mouse Village project
theme: just-the-docs

url: https://braincircuitsbehaviorlab.github.io/mouse-village-web

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

favicon_ico: "/assets/favicon.svg"
logo: "/assets/logo.svg"
